"""empty message

Revision ID: 5141af589b1d
Revises: 5b2011e820da
Create Date: 2022-06-03 14:28:47.330210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5141af589b1d'
down_revision = '5b2011e820da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_taken', sa.Time(), nullable=True))
        batch_op.create_index(batch_op.f('ix_medicines_time_taken'), ['time_taken'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicines_time_taken'))
        batch_op.drop_column('time_taken')

    # ### end Alembic commands ###
