"""users

Revision ID: 537bb352de7a
Revises: b38d2f1cd170
Create Date: 2022-04-17 15:23:49.575999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537bb352de7a'
down_revision = 'b38d2f1cd170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('contact_id', name=op.f('pk_contacts'))
    )
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_index('ix_medicines_name')
        batch_op.create_index(batch_op.f('ix_medicines_name'), ['name'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('lname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('update_privileges', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_users_emergency_contact')
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_fname'), ['fname'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_lname'), ['lname'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_update_privileges'), ['update_privileges'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_users_contact_id_contacts'), 'contacts', ['contact_id'], ['contact_id'])
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_users_contact_id_contacts'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_update_privileges'))
        batch_op.drop_index(batch_op.f('ix_users_lname'))
        batch_op.drop_index(batch_op.f('ix_users_fname'))
        batch_op.create_index('ix_users_username', ['username'], unique=False)
        batch_op.create_index('ix_users_emergency_contact', ['emergency_contact'], unique=False)
        batch_op.drop_column('contact_id')
        batch_op.drop_column('update_privileges')
        batch_op.drop_column('lname')
        batch_op.drop_column('fname')

    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicines_name'))
        batch_op.create_index('ix_medicines_name', ['name'], unique=False)

    op.drop_table('contacts')
    # ### end Alembic commands ###
