"""empty message

Revision ID: 5f47f2da644a
Revises: fedc2a2d3dd4
Create Date: 2022-04-17 16:48:02.560798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f47f2da644a'
down_revision = 'fedc2a2d3dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    op.drop_table('_alembic_tmp_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('lname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('update_privileges', sa.BOOLEAN(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('contact_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.cid'], name='fk_users_contact_id_contacts'),
    sa.PrimaryKeyConstraint('id', name='pk_users')
    )
    op.create_table('contacts',
    sa.Column('cid', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('cid', name='pk_contacts')
    )
    # ### end Alembic commands ###
