"""users

Revision ID: 6324d605f152
Revises: 68fb2e0d208b
Create Date: 2022-04-17 16:42:35.947926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6324d605f152'
down_revision = '68fb2e0d208b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
