"""users

Revision ID: 68fb2e0d208b
Revises: b38d2f1cd170
Create Date: 2022-04-17 16:33:58.108062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68fb2e0d208b'
down_revision = 'b38d2f1cd170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('lname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('update_privileges', sa.Boolean(), nullable=True))
        batch_op.drop_index('ix_users_emergency_contact')
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_fname'), ['fname'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_lname'), ['lname'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_update_privileges'), ['update_privileges'], unique=False)
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_update_privileges'))
        batch_op.drop_index(batch_op.f('ix_users_lname'))
        batch_op.drop_index(batch_op.f('ix_users_fname'))
        batch_op.create_index('ix_users_username', ['username'], unique=False)
        batch_op.create_index('ix_users_emergency_contact', ['emergency_contact'], unique=False)
        batch_op.drop_column('update_privileges')
        batch_op.drop_column('lname')
        batch_op.drop_column('fname')

    # ### end Alembic commands ###
