"""empty message

Revision ID: 8ea27e6ec7d5
Revises: 1b1f17a0fdbb
Create Date: 2022-04-28 23:16:43.798121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea27e6ec7d5'
down_revision = '1b1f17a0fdbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_medicines')
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('cycle_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('cycle_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_medicines',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('dose', sa.INTEGER(), nullable=True),
    sa.Column('period', sa.FLOAT(), nullable=True),
    sa.Column('taken', sa.BOOLEAN(), nullable=True),
    sa.Column('pills', sa.INTEGER(), nullable=True),
    sa.Column('cycle_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], name='fk_medicines_cycle_id_cycles'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_medicines_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_medicines')
    )
    # ### end Alembic commands ###
