"""users

Revision ID: a192bd3f5503
Revises: 6e54476b5063
Create Date: 2022-03-13 17:28:22.958639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a192bd3f5503'
down_revision = '6e54476b5063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_emergency_contact'), ['emergency_contact'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_emergency_contact'))
        batch_op.drop_column('emergency_contact')

    # ### end Alembic commands ###
