"""medicines

Revision ID: b38d2f1cd170
Revises: a192bd3f5503
Create Date: 2022-04-01 19:01:22.826764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38d2f1cd170'
down_revision = 'a192bd3f5503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_index('ix_medicine_amount')
        batch_op.drop_index('ix_medicine_cycle')
        batch_op.drop_index('ix_medicine_dose')
        batch_op.drop_index('ix_medicine_name')
        batch_op.drop_index('ix_medicine_period')
        batch_op.drop_index('ix_medicine_taken')

    op.drop_table('medicine')
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pills', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_medicines_amount')
        batch_op.create_index(batch_op.f('ix_medicines_pills'), ['pills'], unique=False)
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_medicines_pills'))
        batch_op.create_index('ix_medicines_amount', ['amount'], unique=False)
        batch_op.drop_column('pills')

    op.create_table('medicine',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('dose', sa.INTEGER(), nullable=True),
    sa.Column('cycle', sa.INTEGER(), nullable=True),
    sa.Column('period', sa.FLOAT(), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('taken', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_medicine_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_medicine')
    )
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.create_index('ix_medicine_taken', ['taken'], unique=False)
        batch_op.create_index('ix_medicine_period', ['period'], unique=False)
        batch_op.create_index('ix_medicine_name', ['name'], unique=False)
        batch_op.create_index('ix_medicine_dose', ['dose'], unique=False)
        batch_op.create_index('ix_medicine_cycle', ['cycle'], unique=False)
        batch_op.create_index('ix_medicine_amount', ['amount'], unique=False)

    # ### end Alembic commands ###
