"""empty message

Revision ID: f40b630c95a0
Revises: 8ea27e6ec7d5
Create Date: 2022-04-28 23:23:37.460439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40b630c95a0'
down_revision = '8ea27e6ec7d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('cycle_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('cycle_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
