"""patients

Revision ID: fe9622f15561
Revises: 6324d605f152
Create Date: 2022-04-17 16:44:38.312786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9622f15561'
down_revision = '6324d605f152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('cid', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('cid', name=op.f('pk_contacts'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_users_contact_id_contacts'), 'contacts', ['contact_id'], ['cid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_contact_id_contacts'), type_='foreignkey')
        batch_op.drop_column('contact_id')

    op.drop_table('contacts')
    # ### end Alembic commands ###
