"""empty message

Revision ID: fedc2a2d3dd4
Revises: fe9622f15561
Create Date: 2022-04-17 16:46:49.809798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fedc2a2d3dd4'
down_revision = 'fe9622f15561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_users')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_users_contact_id_contacts'), 'contacts', ['contact_id'], ['cid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_contact_id_contacts'), type_='foreignkey')
        batch_op.drop_column('contact_id')

    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('lname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('update_privileges', sa.BOOLEAN(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('contact_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.cid'], name='fk_users_contact_id_contacts'),
    sa.PrimaryKeyConstraint('id', name='pk_users')
    )
    # ### end Alembic commands ###
